cool

diff --git a/usr/share/theinitrd/install/amd64_microcode b/usr/share/theinitrd/install/amd64_microcode
--- a/usr/share/theinitrd/install/amd64_microcode
+++ b/usr/share/theinitrd/install/amd64_microcode
@@ -8,6 +8,16 @@
 
 #. /usr/share/geninit.d/hook-functions
 __TMPEARLYCPIO="$(mktemp "${TMPDIR:-/var/tmp}/mkinitramfs-FW_XXXXXX")" || exit 1
+echo $__TMPEARLYCPIO
+. /home/rzero/.local/src/CORE/theinit/usr/share/geninit.d/hook-functions
+
+verbose()
+{
+    if [ "${verbose}" = "y" ] ; then
+        echo "I: amd64-microcode: $*"
+    fi
+    :
+}
 
 AUCODE_FW_DIR=/lib/firmware/amd-ucode
 AMD64UCODE_INITRAMFS=${AMD64UCODE_INITRAMFS:-early}
@@ -21,25 +31,39 @@ fi
 
 case "${AMD64UCODE_INITRAMFS}" in
     no|0)
+        verbose "disabled by ${AMD64UCODE_CONFIG}"
         exit 0
         ;;
     auto|early)
         ;;
     yes|1)
+        echo "W: amd64-microcode: initramfs mode not supported, using early-initramfs mode" >&2
         AMD64UCODE_INITRAMFS=early
         ;;
     *)
+        echo "E: amd64-microcode: invalid AMD64UCODE_INITRAMFS, using automatic mode" >&2
         AMD64UCODE_INITRAMFS=auto
 esac
+
+if [ "${AMD64UCODE_INITRAMFS}" = "auto" ] ; then
+    grep -q "^vendor_id[[:blank:]]*:[[:blank:]]*.*AuthenticAMD" /proc/cpuinfo || {
+        verbose "no AMD processors detected, nothing to do"
+        exit 0
+    }
+fi
+
+verbose "installing AMD64 microcode into the early initramfs..."
 
 # set during package build to the date from the package *version*
 CHANGELOG_TS=1576627200
 
 EFWD=$(mktemp -d "${TMPDIR:-/var/tmp}/mkinitramfs-EFW_XXXXXXXXXX") || {
+    echo "E: amd64-microcode: cannot create temporary directory" >&2
     exit 1
 }
 # paranoia
 [ ! -d "${EFWD}" ] && {
+    echo "E: amd64-microcode: mktemp -d malfunction" >&2
     exit 1
 }
 
@@ -57,7 +81,13 @@ mkdir -p "${EFWCD}" && \
     # --reproducible requires cpio >= 2.12
     cpio --usage | grep -qs -- "--reproducible" && cpio_reproducible="--reproducible" || true
  } && test -s "${EFWF}" && \
- ( cd "${EFWD}/d" ; find . -print0 | LC_ALL=C sort -z | cpio --null $cpio_reproducible -R 0:0 -H newc -o --quiet  )
+ ( cd "${EFWD}/d" ; find . -print0 | LC_ALL=C sort -z | cpio --null $cpio_reproducible -R 0:0 -H newc -o --quiet > "${EFWE}" ) \
+&& prepend_earlyinitramfs "${EFWE}" || {
+    # something failed somewhere in that pipeline
+    [ -d "${EFWD}" ] && rm -fr "${EFWD}"
+    echo "E: amd64-microcode: failed to create or prepend the early initramfs to the initramfs" >&2
+    exit 0
+}
 
 [ -d "${EFWD}" ] && rm -fr "${EFWD}"
 
